# # ----------destroy all: -----------

# Update.destroy_all
# Project.destroy_all
# User.destroy_all


# # ----------projects (seed prep for many-to-many): -----------

p1 = Project.create!(name:"Circuit Breaker Dashboard with Pivotal")
p2 = Project.create!(name:"Open Tracing with Scala")
p3 = Project.create!(name:"Timing CircleCI Commands")
p4 = Project.create!(name:"Terraforming Monitors")
p5 = Project.create!(name:"Monitoring the Kubernetes Control Plane")
p6 = Project.create!(name:"Collaboration with Tech Ladies")
p7 = Project.create!(name:"Intercom")


# # ----------users with projects seed: -----------


User.create!("username":"htankard0","password_digest":"4f2a876b92f406949edbdb226b1b5c09710d9bf83f35058a2797f7a7710266a4","avatar":"https://randomuser.me/api/portraits/men/54.jpg","first_name":"Hilliard","last_name":"Tankard","email":"Hilliard.Tankard@datadoghq.com","title":"Analyst","team":"Finance","city":"Singapore","love_datadog":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","weekend":"Doggo ipsum such treat big ol doge yapper. Tungg you are doin me a concern.","top_skills":"Ruby on Rails","gender":"female","pronouns":"she/her","projects":[p4,p2,p1,p6,p5],"status":true)
User.create!("username":"bivakhnov1","password_digest":"82a444f2132c97eb0b10d7afbfd6dde5968d96991d45e7fbe8feaa38a5927182","avatar":"http://www.place-puppy.com/203x203","first_name":"Baryram","last_name":"Ivakhnov","email":"Baryram.Ivakhnov@datadoghq.com","title":"UX Designer","team":"Design","city":"Chicago","love_datadog":"Snoot very hand that feed shibe snoot most angery pupper I have ever seen boof pupper very taste wow","weekend":"Snoot very hand that feed shibe snoot most angery pupper I have ever seen boof pupper very taste wow","top_skills":"Blogging","gender":"female","pronouns":"she/her","projects":[p2,p7,p3,p6,p4],"status":false)
User.create!("username":"hpenlington2","password_digest":"7904a44b475fbabb5fa606f81a65068ddb1e158def862d129478e025c0d3a256","avatar":"http://www.place-puppy.com/200x200","first_name":"Humberto","last_name":"Penlington","email":"Humberto.Penlington@datadoghq.com","title":"Director Product Management","team":"Product","city":"San Jose","love_datadog":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","weekend":"Snoot very hand that feed shibe snoot most angery pupper I have ever seen boof pupper very taste wow","top_skills":"Making Chartz","gender":"male","pronouns":"he/him","projects":[p4,p2,p5],"status":true)
User.create!("username":"obartram3","password_digest":"f4b36b7753218444cf61daf667b6d5e8080d4312064af7813e8d1e6d2a285c94","avatar":"https://randomuser.me/api/portraits/men/54.jpg","first_name":"Otes","last_name":"Bartram","email":"Otes.Bartram@datadoghq.com","title":"Director Product Management","team":"Product","city":"Frankfurt","love_datadog":"Maximum borkdrive super chub you are doing me the shock long bois shoober blop pupperino.","weekend":"heckin.","top_skills":"Databases","gender":"male","pronouns":"he/him","projects":[p5,p1,p7],"status":true)
User.create!("username":"mpeebles4","password_digest":"7c609310f1fa535c1adae6ebabb1b3582308140921ee45df6d9e7af42b923983","avatar":"http://www.place-puppy.com/201x201","first_name":"Margie","last_name":"Peebles","email":"Margie.Peebles@datadoghq.com","title":"Director","team":"Finance","city":"Dublin","love_datadog":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","weekend":"heckin.","top_skills":"UX Design","gender":"male","pronouns":"he/him","projects":[p1,p4,p7,p6],"status":true)
User.create!("username":"ccharrette5","password_digest":"b933feb789c2028e7e7778248a401ebb6d1aab48c1d0ae2555ba9d718cb1a3d8","avatar":"https://avatars.githubusercontent.com/u/2196208?s=200","first_name":"Ciro","last_name":"Charrette","email":"Ciro.Charrette@datadoghq.com","title":"Analyst","team":"Finance","city":"Chicago","love_datadog":"Maximum borkdrive super chub you are doing me the shock long bois shoober blop pupperino.","weekend":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","top_skills":"UX Design","gender":"female","pronouns":"she/her","projects":[p1,p7,p5,p4,p2],"status":true)
User.create!("username":"kkirgan6","password_digest":"e7e0a7980fddc09ac9c65f0908d19f7a311ff6e3f7ac9d5e5bfc5389490d6111","avatar":"https://avatars.githubusercontent.com/u/4694092?s=200","first_name":"Klement","last_name":"Kirgan","email":"Klement.Kirgan@datadoghq.com","title":"Developer","team":"Engineering","city":"Portland","love_datadog":"heckin.","weekend":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","top_skills":"Databases","gender":"female","pronouns":"she/her","projects":[p4,p2,p7,p3],"status":true)
User.create!("username":"eshitliff7","password_digest":"574bce7ac22286385f6faccc2d0a2fae721867fdcd1e88320cdbaa94d5a87ff4","avatar":"http://www.place-puppy.com/202x202","first_name":"Ermentrude","last_name":"Shitliff","email":"Ermentrude.Shitliff@datadoghq.com","title":"Engineer","team":"Engineering","city":"Tokyo","love_datadog":"Maximum borkdrive super chub you are doing me the shock long bois shoober blop pupperino.","weekend":"Very hand that feed shibe yapper much ruin diet. Yapper noodle horse ruff tungg","top_skills":"DevOps","gender":"female","pronouns":"she/her","projects":[p4,p3,p7,p6],"status":true)
User.create!("username":"twolledge8","password_digest":"450891d5b1b9a3ecaa2f4983997da18c9ae884fa2dec716f36acdcd3ed3bf145","avatar":"https://randomuser.me/api/portraits/women/36.jpg","first_name":"Tyrus","last_name":"Wolledge","email":"Tyrus.Wolledge@datadoghq.com","title":"HR Generalist","team":"Human Resources","city":"Paris","love_datadog":"Doggo ipsum such treat big ol doge yapper. Tungg you are doin me a concern.","weekend":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","top_skills":"Databases","gender":"male","pronouns":"he/him","projects":[p2,p3,p4,p7],"status":false)
User.create!("username":"fmenichini9","password_digest":"535f75cec0843fce66fe0df38646b040375f4e08b98bf88c739f1389993f1c64","avatar":"http://www.place-puppy.com/203x203","first_name":"Faye","last_name":"Menichini","email":"Faye.Menichini@datadoghq.com","title":"UX Manager","team":"Design","city":"Paris","love_datadog":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","weekend":"Doggo ipsum such treat big ol doge yapper. Tungg you are doin me a concern.","top_skills":"Javascript","gender":"male","pronouns":"he/him","projects":[p1,p7,p4,p3,p2],"status":true)
User.create!("username":"eclixbya","password_digest":"a1d64194bb839e49214f56e4fce2bc469f427ae84b6805b472bac163d3fd8e30","avatar":"https://avatars.githubusercontent.com/u/767836?s=200","first_name":"Erie","last_name":"Clixby","email":"Erie.Clixby@datadoghq.com","title":"Director","team":"Finance","city":"Seoul","love_datadog":"Waggy wags doing me a frighten woofer very taste wow.","weekend":"Waggy wags doing me a frighten woofer very taste wow.","top_skills":"Blogging","gender":"male","pronouns":"he/him","projects":[p4,p2,p1,p7,p5],"status":true)
User.create!("username":"pmackibbonb","password_digest":"3ef6fb41356e080cb6192cdf56832582fbfba0737a17594ad6b0ccc9aff8ab63","avatar":"https://randomuser.me/api/portraits/men/55.jpg","first_name":"Powell","last_name":"MacKibbon","email":"Powell.MacKibbon@datadoghq.com","title":"Developer","team":"Engineering","city":"","love_datadog":"Maximum borkdrive super chub you are doing me the shock long bois shoober blop pupperino.","weekend":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","top_skills":"MVC","gender":"male","pronouns":"he/him","projects":[p2,p7,p3],"status":false)
User.create!("username":"hbastowc","password_digest":"4512c3d2fdfd8ec81346ea73be84e630c3bb3f48f7376f8652bee5e1420c13ff","avatar":"https://randomuser.me/api/portraits/men/39.jpg","first_name":"Hillery","last_name":"Bastow","email":"Hillery.Bastow@datadoghq.com","title":"UX Designer","team":"Design","city":"","love_datadog":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","weekend":"Maximum borkdrive super chub you are doing me the shock long bois shoober blop pupperino.","top_skills":"Databases","gender":"female","pronouns":"she/her","projects":[p7,p2,p3],"status":true)
User.create!("username":"arobartsd","password_digest":"06221f54e2393596922d8a8362421b997a8995c42c45ecbd6dbd67ad2e2fe966","avatar":"http://www.place-puppy.com/201x201","first_name":"Abbie","last_name":"Robarts","email":"Abbie.Robarts@datadoghq.com","title":"Project Lead","team":"Engineering","city":"","love_datadog":"Waggy wags doing me a frighten woofer very taste wow.","weekend":"Doggo ipsum such treat big ol doge yapper. Tungg you are doin me a concern.","top_skills":"Creating Personas","gender":"female","pronouns":"she/her","projects":[p6,p1,p7,p4],"status":false)
User.create!("username":"pbolesworthe","password_digest":"7be479354f56f03ed7ea5c1a9022fe744f1295cd6cea3970aa690430c30c3fad","avatar":"http://www.place-puppy.com/203x203","first_name":"Paulita","last_name":"Bolesworth","email":"Paulita.Bolesworth@datadoghq.com","title":"Engineer","team":"Engineering","city":"Boston","love_datadog":"heckin.","weekend":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","top_skills":"Marketing","gender":"male","pronouns":"he/him","projects":[p1,p2,p3],"status":false)
User.create!("username":"mthewf","password_digest":"f196ea4286113b7f69b3dbccd23de9754c2515798131828161f4be2f7c195848","avatar":"https://randomuser.me/api/portraits/women/2.jpg","first_name":"Matthus","last_name":"Thew","email":"Matthus.Thew@datadoghq.com","title":"Project Lead","team":"Engineering","city":"Boston","love_datadog":"heckin.","weekend":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","top_skills":"Marketing","gender":"gender neutral","pronouns":"they/them","projects":[p1,p5,p4],"status":true)
User.create!("username":"iheightg","password_digest":"68600b8ad50ffe7dc0233d4097a97afbbb6829274701d9cb6498733b50ca3731","avatar":"https://randomuser.me/api/portraits/women/50.jpg","first_name":"Iorgos","last_name":"Height","email":"Iorgos.Height@datadoghq.com","title":"Engineer","team":"Engineering","city":"Singapore","love_datadog":"Doggo ipsum such treat big ol doge yapper. Tungg you are doin me a concern.","weekend":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","top_skills":"MVC","gender":"female","pronouns":"she/her","projects":[p1,p6,p7,p3],"status":false)
User.create!("username":"mmurgatroydh","password_digest":"412f1ba6b6d2354f0d67e78ead2bbaf61fedaa745127ba673d36cae7181b9e99","avatar":"https://avatars.githubusercontent.com/u/1510807?s=200","first_name":"Maribelle","last_name":"Murgatroyd","email":"Maribelle.Murgatroyd@datadoghq.com","title":"Analyst","team":"Finance","city":"Denver","love_datadog":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","weekend":"Maximum borkdrive super chub you are doing me the shock long bois shoober blop pupperino.","top_skills":"Financial Planning","gender":"female","pronouns":"she/her","projects":[p1,p4,p2,p7],"status":true)
User.create!("username":"sstrattoni","password_digest":"157850c5c3ec4f6561856f6fc2c40901ef06678c94682bfe1cfa76b08e07a0b5","avatar":"https://randomuser.me/api/portraits/women/16.jpg","first_name":"Siward","last_name":"Stratton","email":"Siward.Stratton@datadoghq.com","title":"Director","team":"Finance","city":"Washington DC","love_datadog":"Doggo ipsum such treat big ol doge yapper. Tungg you are doin me a concern.","weekend":"Maximum borkdrive super chub you are doing me the shock long bois shoober blop pupperino.","top_skills":"Blogging","gender":"male","pronouns":"he/him","projects":[p4,p1,p2,p7,p5],"status":true)
User.create!("username":"dlegatej","password_digest":"53f4862fb5a887faa96e1210b2b7b43f4e08613e564c821f49bafa6ef96f2f6c","avatar":"http://www.place-puppy.com/202x202","first_name":"Dov","last_name":"Legate","email":"Dov.Legate@datadoghq.com","title":"Product Manager","team":"Product","city":"Sydney","love_datadog":"Maximum borkdrive super chub you are doing me the shock long bois shoober blop pupperino.","weekend":"heckin.","top_skills":"Project Management","gender":"female","pronouns":"she/her","projects":[p3,p4,p1,p5],"status":false)
User.create!("username":"sritsonk","password_digest":"12c36cea5f6a5228634f8a82975184a91ac50082bfecc971556acac16a8c2a95","avatar":"https://randomuser.me/api/portraits/women/16.jpg","first_name":"Sapphire","last_name":"Ritson","email":"Sapphire.Ritson@datadoghq.com","title":"Manager","team":"Finance","city":"Denver","love_datadog":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","weekend":"heckin.","top_skills":"Project Management","gender":"male","pronouns":"he/him","projects":[p6,p4,p1,p3,p2],"status":false)
User.create!("username":"lvasilikl","password_digest":"14f41df7de6185ca20eed71da21bb2a820438aba9b2ea3e0ae4873ff8bbc7076","avatar":"http://www.place-puppy.com/201x201","first_name":"Lannie","last_name":"Vasilik","email":"Lannie.Vasilik@datadoghq.com","title":"Director","team":"Finance","city":"Stockholm","love_datadog":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","weekend":"Snoot very hand that feed shibe snoot most angery pupper I have ever seen boof pupper very taste wow","top_skills":"Making the client happy","gender":"male","pronouns":"he/him","projects":[p4,p7,p3],"status":true)
User.create!("username":"lstempm","password_digest":"b3c5f398e4b24561b51b773b8345bac6055a1cccc90258bcbf5c7582756bf8e0","avatar":"https://avatars.githubusercontent.com/u/577978?s=200","first_name":"Launce","last_name":"Stemp","email":"Launce.Stemp@datadoghq.com","title":"Engineer","team":"Engineering","city":"Dublin","love_datadog":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","weekend":"Very hand that feed shibe yapper much ruin diet. Yapper noodle horse ruff tungg","top_skills":"Full-stack development","gender":"female","pronouns":"she/her","projects":[p2,p6,p1,p4],"status":false)
User.create!("username":"skirmann","password_digest":"362299023e9afb9105151324099c0220756500501baacf226eb33d9a27bd5409","avatar":"https://avatars.githubusercontent.com/u/767836?s=200","first_name":"Sindee","last_name":"Kirman","email":"Sindee.Kirman@datadoghq.com","title":"UX Designer","team":"Design","city":"Portland","love_datadog":"Snoot very hand that feed shibe snoot most angery pupper I have ever seen boof pupper very taste wow","weekend":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","top_skills":"DevOps","gender":"male","pronouns":"he/him","projects":[p3,p5,p2,p6],"status":false)
User.create!("username":"tuvedaleo","password_digest":"c5d8f9aa6daf44d7d9fb135e28595d54e84e705f8d40f7f92e342978dab4aa0f","avatar":"https://randomuser.me/api/portraits/women/16.jpg","first_name":"Tabatha","last_name":"Uvedale","email":"Tabatha.Uvedale@datadoghq.com","title":"UX Manager","team":"Design","city":"São Paulo","love_datadog":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","weekend":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","top_skills":"Product magic","gender":"female","pronouns":"she/her","projects":[p4,p3,p1],"status":false)
User.create!("username":"vtwistp","password_digest":"4414783b046308b2d38d92cab4c9f669b009beb9a84d1f8c8b03d2dc8903471b","avatar":"https://avatars.githubusercontent.com/u/1712393?s=200","first_name":"Verena","last_name":"Twist","email":"Verena.Twist@datadoghq.com","title":"HR Generalist","team":"Human Resources","city":"Seoul","love_datadog":"Doggo ipsum such treat big ol doge yapper. Tungg you are doin me a concern.","weekend":"heckin.","top_skills":"Making Chartz","gender":"male","pronouns":"he/him","projects":[p6,p4,p2,p3,p1],"status":true)
User.create!("username":"rpondjonesq","password_digest":"01cfd605f0114801c9b92d54abae45aec3fa39ec536af9426a10705cb63ddb38","avatar":"https://avatars.githubusercontent.com/u/15220759?s=200","first_name":"Ricca","last_name":"Pond-Jones","email":"Ricca.Pond-Jones@datadoghq.com","title":"UX Manager","team":"Design","city":"Seattle","love_datadog":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","weekend":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","top_skills":"Making the client happy","gender":"gender neutral","pronouns":"they/them","projects":[p4,p1,p7,p3],"status":false)
User.create!("username":"gwahnerr","password_digest":"f8e4992cb449b79fc1b5ef345cfd2aa34d23725b946d98d3fd8d8dae32aeec5a","avatar":"https://randomuser.me/api/portraits/men/39.jpg","first_name":"Gertruda","last_name":"Wahner","email":"Gertruda.Wahner@datadoghq.com","title":"Analyst","team":"Finance","city":"Portland","love_datadog":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","weekend":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","top_skills":"Javascript","gender":"female","pronouns":"she/her","projects":[p2,p4,p7],"status":false)
User.create!("username":"hhulkss","password_digest":"b7fba09bec288f66ea58c09c8cf135b6ea9803b8cf33a175e7dca074940cc6e6","avatar":"https://randomuser.me/api/portraits/women/50.jpg","first_name":"Hubey","last_name":"Hulks","email":"Hubey.Hulks@datadoghq.com","title":"UX Manager","team":"Design","city":"London","love_datadog":"heckin.","weekend":"heckin.","top_skills":"Project Management","gender":"male","pronouns":"he/him","projects":[p6,p1,p5,p2],"status":false)
User.create!("username":"nguppeyt","password_digest":"b77f87bb59368bb5212f2b36892360e848001b5c9b25f57c3a8be0164f953f2f","avatar":"https://randomuser.me/api/portraits/women/50.jpg","first_name":"Nikolos","last_name":"Guppey","email":"Nikolos.Guppey@datadoghq.com","title":"HR Generalist","team":"Human Resources","city":"New York City","love_datadog":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","weekend":"Waggy wags doing me a frighten woofer very taste wow.","top_skills":"Python","gender":"gender neutral","pronouns":"they/them","projects":[p1,p4,p3],"status":true)
User.create!("username":"agrundellu","password_digest":"1a6aa305ffb847cd6f5ea0013fc533302d13e9c99f3d32d6525dcb1d5f2e9a16","avatar":"https://randomuser.me/api/portraits/men/54.jpg","first_name":"Alexina","last_name":"Grundell","email":"Alexina.Grundell@datadoghq.com","title":"UX Manager","team":"Design","city":"Dublin","love_datadog":"Doggo ipsum such treat big ol doge yapper. Tungg you are doin me a concern.","weekend":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","top_skills":"Blogging","gender":"male","pronouns":"he/him","projects":[p2,p4,p1],"status":true)
User.create!("username":"kclimpsonv","password_digest":"a20baaf52527c19496860bd881674dd5a8c447e054136db02b871f68527bd13f","avatar":"https://randomuser.me/api/portraits/women/50.jpg","first_name":"Kristofer","last_name":"Climpson","email":"Kristofer.Climpson@datadoghq.com","title":"Developer","team":"Engineering","city":"Dublin","love_datadog":"Waggy wags doing me a frighten woofer very taste wow.","weekend":"Waggy wags doing me a frighten woofer very taste wow.","top_skills":"Project Management","gender":"gender neutral","pronouns":"they/them","projects":[p7,p4,p3],"status":false)
User.create!("username":"ywellerw","password_digest":"23db4e1ca2f624c72a2ec18ebf71fc3c58475ef9dd9a169d601f4a26b1cb5f6f","avatar":"https://avatars.githubusercontent.com/u/15220759?s=200","first_name":"Yetty","last_name":"Weller","email":"Yetty.Weller@datadoghq.com","title":"UX Designer","team":"Design","city":"Boston","love_datadog":"Snoot very hand that feed shibe snoot most angery pupper I have ever seen boof pupper very taste wow","weekend":"heckin.","top_skills":"Creating Personas","gender":"male","pronouns":"he/him","projects":[p1,p4,p6,p3,p2],"status":false)
User.create!("username":"sbuckhurstx","password_digest":"6085a9e0b2f9a5e240b9d966ae4f2b2d6d84c1dcc6cc8d66c1e1a638db3d8aff","avatar":"https://randomuser.me/api/portraits/women/9.jpg","first_name":"Selle","last_name":"Buckhurst","email":"Selle.Buckhurst@datadoghq.com","title":"Product Manager","team":"Product","city":"Frankfurt","love_datadog":"heckin.","weekend":"Very hand that feed shibe yapper much ruin diet. Yapper noodle horse ruff tungg","top_skills":"MVC","gender":"gender neutral","pronouns":"they/them","projects":[p7,p3,p6,p5,p4],"status":true)
User.create!("username":"eschnittery","password_digest":"76228f657f9626f0652baa554e40fe01cc0fce8b2a77a0fb134cb96b79ae22e1","avatar":"https://avatars.githubusercontent.com/u/2196208?s=200","first_name":"Ewen","last_name":"Schnitter","email":"Ewen.Schnitter@datadoghq.com","title":"HR Director","team":"Human Resources","city":"Amsterdam","love_datadog":"Snoot very hand that feed shibe snoot most angery pupper I have ever seen boof pupper very taste wow","weekend":"Snoot very hand that feed shibe snoot most angery pupper I have ever seen boof pupper very taste wow","top_skills":"Databases","gender":"female","pronouns":"she/her","projects":[p4,p3,p7,p5,p2],"status":false)
User.create!("username":"lfantiniz","password_digest":"36d6b40cbdb6cdb13e5a6f662f0b7529643ebbca2cec42293350113227ea60d9","avatar":"https://avatars.githubusercontent.com/u/22248726?s=200","first_name":"Lindie","last_name":"Fantini","email":"Lindie.Fantini@datadoghq.com","title":"HR Director","team":"Human Resources","city":"Portland","love_datadog":"Waggy wags doing me a frighten woofer very taste wow.","weekend":"Snoot very hand that feed shibe snoot most angery pupper I have ever seen boof pupper very taste wow","top_skills":"Blogging","gender":"male","pronouns":"he/him","projects":[p6,p2,p5],"status":false)
User.create!("username":"ffrancescoccio10","password_digest":"ac248a120a259809e2ece695611108b93bffd1c4df4e2f95235ba5dc4f8de97f","avatar":"https://avatars.githubusercontent.com/u/12176807?s=200","first_name":"Farley","last_name":"Francescoccio","email":"Farley.Francescoccio@datadoghq.com","title":"UX Manager","team":"Design","city":"New York City","love_datadog":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","weekend":"Doggo ipsum such treat big ol doge yapper. Tungg you are doin me a concern.","top_skills":"Financial Planning","gender":"gender neutral","pronouns":"they/them","projects":[p6,p1,p2],"status":true)
User.create!("username":"bsea11","password_digest":"f7c962bdc5e3be5c75f4bb3be13fcc2a97d0227800f9b14de61cbb8c45d461d3","avatar":"https://avatars.githubusercontent.com/u/1510807?s=200","first_name":"Bari","last_name":"Sea","email":"Bari.Sea@datadoghq.com","title":"HR Director","team":"Human Resources","city":"Tokyo","love_datadog":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","weekend":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","top_skills":"Ruby on Rails","gender":"male","pronouns":"he/him","projects":[p2,p6,p4],"status":true)
User.create!("username":"tpettigrew12","password_digest":"d48fe1311d1425364b9806c78faa9aea28a6d57d68c03a640e2440aea3dcbc50","avatar":"https://randomuser.me/api/portraits/men/55.jpg","first_name":"Terza","last_name":"Pettigrew","email":"Terza.Pettigrew@datadoghq.com","title":"Developer","team":"Engineering","city":"New York City","love_datadog":"Maximum borkdrive super chub you are doing me the shock long bois shoober blop pupperino.","weekend":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","top_skills":"Databases","gender":"female","pronouns":"she/her","projects":[p4,p2,p7,p1],"status":false)
User.create!("username":"elindley13","password_digest":"b90a0f651afb5e30b88dc620ec5a173df98cd249710c2b287729e9a2de401b9e","avatar":"https://avatars.githubusercontent.com/u/577978?s=200","first_name":"Ernestus","last_name":"Lindley","email":"Ernestus.Lindley@datadoghq.com","title":"Director","team":"Finance","city":"Chicago","love_datadog":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","weekend":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","top_skills":"Databases","gender":"gender neutral","pronouns":"they/them","projects":[p7,p4,p3],"status":true)
User.create!("username":"lfyfield14","password_digest":"6ac3771be23b3f31a44a2ba6f1b042cf7347b558b002d2c4765b2c198ee3559e","avatar":"https://randomuser.me/api/portraits/women/16.jpg","first_name":"Lesley","last_name":"Fyfield","email":"Lesley.Fyfield@datadoghq.com","title":"HR Director","team":"Human Resources","city":"Stockholm","love_datadog":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","weekend":"heckin.","top_skills":"Blogging","gender":"female","pronouns":"she/her","projects":[p2,p3,p7],"status":false)
User.create!("username":"wginnelly15","password_digest":"48582334b3358bb8a8a2ff2b7c7e913d44ff1c3e882433cfec107c56ce118728","avatar":"http://www.place-puppy.com/203x203","first_name":"Wald","last_name":"Ginnelly","email":"Wald.Ginnelly@datadoghq.com","title":"Developer","team":"Engineering","city":"London","love_datadog":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","weekend":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","top_skills":"Making the client happy","gender":"gender neutral","pronouns":"they/them","projects":[p4,p6,p5,p2,p7],"status":false)
User.create!("username":"meaken16","password_digest":"e37987335dbc8562a4a22d7a4f9ba94db95a8899d55dc3035fafd840c6bcfd22","avatar":"https://avatars.githubusercontent.com/u/12176807?s=200","first_name":"Morissa","last_name":"Eaken","email":"Morissa.Eaken@datadoghq.com","title":"Director Product Management","team":"Product","city":"Dublin","love_datadog":"Very hand that feed shibe yapper much ruin diet. Yapper noodle horse ruff tungg","weekend":"Maximum borkdrive super chub you are doing me the shock long bois shoober blop pupperino.","top_skills":"MVC","gender":"gender neutral","pronouns":"they/them","projects":[p3,p1,p4,p6,p2],"status":true)
User.create!("username":"aconford17","password_digest":"092557a8d421c2e1e3ee460e05a1ed41f228c7ad8e06b4b38197d0fafddacb18","avatar":"https://avatars.githubusercontent.com/u/2196208?s=200","first_name":"Armand","last_name":"Conford","email":"Armand.Conford@datadoghq.com","title":"Developer","team":"Engineering","city":"Portland","love_datadog":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","weekend":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","top_skills":"RESTful APIs","gender":"female","pronouns":"she/her","projects":[p3,p7,p2,p1,p4],"status":false)
User.create!("username":"hbaress18","password_digest":"9f12c991ce6b0d5da64b89396ffd63ab157128c0215b766637626bb310f3889a","avatar":"http://www.place-puppy.com/202x202","first_name":"Helena","last_name":"Baress","email":"Helena.Baress@datadoghq.com","title":"Developer","team":"Engineering","city":"Amsterdam","love_datadog":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","weekend":"Very hand that feed shibe yapper much ruin diet. Yapper noodle horse ruff tungg","top_skills":"DevOps","gender":"gender neutral","pronouns":"they/them","projects":[p2,p7,p5,p4,p6],"status":true)
User.create!("username":"hliddel19","password_digest":"56376d25bb6498eed332686ebe929a60bf5c07b1680bfd9aa14c0754ee6d509b","avatar":"https://randomuser.me/api/portraits/men/23.jpg","first_name":"Haley","last_name":"Liddel","email":"Haley.Liddel@datadoghq.com","title":"UX Manager","team":"Design","city":"Denver","love_datadog":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","weekend":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","top_skills":"DevOps","gender":"female","pronouns":"she/her","projects":[p6,p3,p5,p1,p4],"status":false)
User.create!("username":"eagett1a","password_digest":"f137e5bfd26a2a901e9bb635cc20ef60b31a140208249f3dc4d3c7368ba8a12b","avatar":"https://avatars.githubusercontent.com/u/767836?s=200","first_name":"Eran","last_name":"Agett","email":"Eran.Agett@datadoghq.com","title":"UX Manager","team":"Design","city":"","love_datadog":"Very hand that feed shibe yapper much ruin diet. Yapper noodle horse ruff tungg","weekend":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","top_skills":"Fly Tweets","gender":"gender neutral","pronouns":"they/them","projects":[p5,p2,p4,p7],"status":true)
User.create!("username":"nbentote1b","password_digest":"c48e2e002177b54749926db1d740c3678aff74a5eacf27e50fd19652af237fe8","avatar":"http://www.place-puppy.com/202x202","first_name":"Normand","last_name":"Bentote","email":"Normand.Bentote@datadoghq.com","title":"Project Lead","team":"Engineering","city":"Dublin","love_datadog":"Maximum borkdrive super chub you are doing me the shock long bois shoober blop pupperino.","weekend":"Waggy wags doing me a frighten woofer very taste wow.","top_skills":"Python","gender":"gender neutral","pronouns":"they/them","projects":[p7,p5,p4,p6,p3],"status":true)
User.create!("username":"mbaggarley1c","password_digest":"a1c39e95c0191aa63d32b5488cd066b0a38a154fc22fcabdd9cf0bdab80a50ad","avatar":"https://avatars.githubusercontent.com/u/2860499?s=200","first_name":"Melisa","last_name":"Baggarley","email":"Melisa.Baggarley@datadoghq.com","title":"Manager","team":"Finance","city":"London","love_datadog":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","weekend":"Very hand that feed shibe yapper much ruin diet. Yapper noodle horse ruff tungg","top_skills":"Marketing","gender":"gender neutral","pronouns":"they/them","projects":[p6,p3,p4,p5],"status":false)
User.create!("username":"dellaway1d","password_digest":"78083461ee3283941f290d012ab12eac1fb86377753419613e7bf703fc9eee1b","avatar":"https://randomuser.me/api/portraits/men/55.jpg","first_name":"Dyna","last_name":"Ellaway","email":"Dyna.Ellaway@datadoghq.com","title":"Developer","team":"Engineering","city":"Dublin","love_datadog":"Very hand that feed shibe yapper much ruin diet. Yapper noodle horse ruff tungg","weekend":"Waggy wags doing me a frighten woofer very taste wow.","top_skills":"RESTful APIs","gender":"gender neutral","pronouns":"they/them","projects":[p4,p1,p5,p6],"status":true)
User.create!("username":"mgentzsch1e","password_digest":"343a0b0a49114027ed830c6bbe7cf9f01749be7b98c58fd80d47239045c16984","avatar":"https://avatars.githubusercontent.com/u/767836?s=200","first_name":"Meier","last_name":"Gentzsch","email":"Meier.Gentzsch@datadoghq.com","title":"Analyst","team":"Finance","city":"São Paulo","love_datadog":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","weekend":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","top_skills":"Creating Personas","gender":"male","pronouns":"he/him","projects":[p7,p3,p1],"status":true)
User.create!("username":"hansett1f","password_digest":"d5f05275bdd0833470a9144dbfe2d2d2cac7cd851763f23b7585e131e1f8ae93","avatar":"https://randomuser.me/api/portraits/women/9.jpg","first_name":"Hugibert","last_name":"Ansett","email":"Hugibert.Ansett@datadoghq.com","title":"HR Director","team":"Human Resources","city":"Singapore","love_datadog":"Waggy wags doing me a frighten woofer very taste wow.","weekend":"Snoot very hand that feed shibe snoot most angery pupper I have ever seen boof pupper very taste wow","top_skills":"Product magic","gender":"gender neutral","pronouns":"they/them","projects":[p3,p7,p1],"status":true)
User.create!("username":"bboake1g","password_digest":"e7bcc70fbb946b4597c5f4be2e2075dc32673651db487ccc0c2fbb30ba908681","avatar":"http://www.place-puppy.com/201x201","first_name":"Bernelle","last_name":"Boake","email":"Bernelle.Boake@datadoghq.com","title":"Project Lead","team":"Engineering","city":"Warsaw","love_datadog":"Doggo ipsum such treat big ol doge yapper. Tungg you are doin me a concern.","weekend":"Maximum borkdrive super chub you are doing me the shock long bois shoober blop pupperino.","top_skills":"Making Chartz","gender":"male","pronouns":"he/him","projects":[p5,p1,p4,p7],"status":true)
User.create!("username":"cbosden1h","password_digest":"2e046f6c5d4ea04a76427e8dc4219f0323a658b4c0e777abf379ef8f884bcb2c","avatar":"https://avatars.githubusercontent.com/u/15220759?s=200","first_name":"Claudell","last_name":"Bosden","email":"Claudell.Bosden@datadoghq.com","title":"Director","team":"Finance","city":"New York City","love_datadog":"Maximum borkdrive super chub you are doing me the shock long bois shoober blop pupperino.","weekend":"Doggo ipsum such treat big ol doge yapper. Tungg you are doin me a concern.","top_skills":"Databases","gender":"gender neutral","pronouns":"they/them","projects":[p6,p1,p3,p2],"status":false)
User.create!("username":"wjohns1i","password_digest":"9de6ea1ea6dab145e9a32c1b2e4c5a5d01b09dc68eb5a8ea2b4284ce0d35010a","avatar":"https://avatars.githubusercontent.com/u/12176807?s=200","first_name":"Willdon","last_name":"Johns","email":"Willdon.Johns@datadoghq.com","title":"Director Product Management","team":"Product","city":"New York City","love_datadog":"Very hand that feed shibe yapper much ruin diet. Yapper noodle horse ruff tungg","weekend":"Snoot very hand that feed shibe snoot most angery pupper I have ever seen boof pupper very taste wow","top_skills":"DevOps","gender":"gender neutral","pronouns":"they/them","projects":[p7,p6,p3],"status":true)
User.create!("username":"tlearmond1j","password_digest":"9e71d9972e16fc051b4d90ea9589625c077c48de9e7f13e6606fc6d39cc30426","avatar":"http://www.place-puppy.com/200x200","first_name":"Tallie","last_name":"Learmond","email":"Tallie.Learmond@datadoghq.com","title":"Analyst","team":"Finance","city":"Portland","love_datadog":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","weekend":"Doggo ipsum such treat big ol doge yapper. Tungg you are doin me a concern.","top_skills":"DevOps","gender":"female","pronouns":"she/her","projects":[p1,p2,p6],"status":true)
User.create!("username":"blongshaw1k","password_digest":"b1d2343105e1db7d3b02e4287c31d7f676d918e45fbff8c948691bb6a15d27c3","avatar":"https://avatars.githubusercontent.com/u/1712393?s=200","first_name":"Benjie","last_name":"Longshaw","email":"Benjie.Longshaw@datadoghq.com","title":"Analyst","team":"Finance","city":"Tokyo","love_datadog":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","weekend":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","top_skills":"Creating Personas","gender":"gender neutral","pronouns":"they/them","projects":[p5,p7,p2,p4,p6],"status":false)
User.create!("username":"crewan1l","password_digest":"68984082820be9324900dd66dc5a93773775b22a56effef820a448ea4f9c6df4","avatar":"https://randomuser.me/api/portraits/women/2.jpg","first_name":"Christean","last_name":"Rewan","email":"Christean.Rewan@datadoghq.com","title":"UX Manager","team":"Design","city":"Amsterdam","love_datadog":"Doggo ipsum such treat big ol doge yapper. Tungg you are doin me a concern.","weekend":"Very hand that feed shibe yapper much ruin diet. Yapper noodle horse ruff tungg","top_skills":"Creating Personas","gender":"gender neutral","pronouns":"they/them","projects":[p1,p6,p2,p3,p4],"status":false)
User.create!("username":"hlethcoe1m","password_digest":"50ef6e83b38d7d2abc6565154a0e7bcaa1319d3004fb3d15956925d4fef73a5c","avatar":"http://www.place-puppy.com/200x200","first_name":"Hatti","last_name":"Lethcoe","email":"Hatti.Lethcoe@datadoghq.com","title":"Director Product Management","team":"Product","city":"Singapore","love_datadog":"heckin.","weekend":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","top_skills":"Blogging","gender":"gender neutral","pronouns":"they/them","projects":[p5,p2,p7,p1],"status":true)
User.create!("username":"ctovey1n","password_digest":"ab4c31eb228d063acad83b690801c45ab1e6f24ae32d77acbd622f8fbf2bc287","avatar":"https://randomuser.me/api/portraits/men/39.jpg","first_name":"Carolus","last_name":"Tovey","email":"Carolus.Tovey@datadoghq.com","title":"Director Product Management","team":"Product","city":"Dublin","love_datadog":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","weekend":"heckin.","top_skills":"Databases","gender":"male","pronouns":"he/him","projects":[p4,p6,p1,p5],"status":false)
User.create!("username":"ssyvret1o","password_digest":"e8ce725d745102411280dc775edfbb0d2336a4c6180096a8dd55386985d3853e","avatar":"http://www.place-puppy.com/202x202","first_name":"Sibby","last_name":"Syvret","email":"Sibby.Syvret@datadoghq.com","title":"Director Product Management","team":"Product","city":"Melbourne","love_datadog":"heckin.","weekend":"heckin.","top_skills":"Ruby on Rails","gender":"male","pronouns":"he/him","projects":[p2,p3,p1,p6,p7],"status":true)
User.create!("username":"dcostell1p","password_digest":"0b8207050671ab44e6d882605dd5fb282fb932522394b9a78d828afeb6c01ece","avatar":"https://randomuser.me/api/portraits/women/36.jpg","first_name":"Dexter","last_name":"Costell","email":"Dexter.Costell@datadoghq.com","title":"UX Designer","team":"Design","city":"Sydney","love_datadog":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","weekend":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","top_skills":"Python","gender":"male","pronouns":"he/him","projects":[p3,p5,p1],"status":true)
User.create!("username":"bjakov1q","password_digest":"5d156cfc0ef85dbb027cc4139f8ec327413e429f53a78be2531ddd4909d61714","avatar":"https://avatars.githubusercontent.com/u/2196208?s=200","first_name":"Brockie","last_name":"Jakov","email":"Brockie.Jakov@datadoghq.com","title":"Product Manager","team":"Product","city":"Warsaw","love_datadog":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","weekend":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","top_skills":"Full-stack development","gender":"female","pronouns":"she/her","projects":[p5,p1,p3],"status":false)
User.create!("username":"mcattroll1r","password_digest":"5ea7f6fe46385d8ba9a8154df94457515e585acfa9c6aa76d74b0bb3ec4c3fec","avatar":"https://randomuser.me/api/portraits/men/39.jpg","first_name":"Manya","last_name":"Cattroll","email":"Manya.Cattroll@datadoghq.com","title":"UX Manager","team":"Design","city":"São Paulo","love_datadog":"Waggy wags doing me a frighten woofer very taste wow.","weekend":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","top_skills":"Project Management","gender":"male","pronouns":"he/him","projects":[p4,p1,p2],"status":false)
User.create!("username":"dhaslocke1s","password_digest":"9dce7c201a6f59de5e233776797b362f593f129e76d057792632b2a7a876ec1b","avatar":"https://avatars.githubusercontent.com/u/1712393?s=200","first_name":"Denny","last_name":"Haslock(e)","email":"Denny.Haslock(e)@datadoghq.com","title":"Director Product Management","team":"Product","city":"Boston","love_datadog":"Maximum borkdrive super chub you are doing me the shock long bois shoober blop pupperino.","weekend":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","top_skills":"Blogging","gender":"gender neutral","pronouns":"they/them","projects":[p2,p1,p4,p3],"status":true)
User.create!("username":"wbraden1t","password_digest":"4c55a3d65c075006c662622c4e104799789c35c589b5a1d3704ee1f12695a8dd","avatar":"https://randomuser.me/api/portraits/women/36.jpg","first_name":"Washington","last_name":"Braden","email":"Washington.Braden@datadoghq.com","title":"Analyst","team":"Finance","city":"Singapore","love_datadog":"Maximum borkdrive super chub you are doing me the shock long bois shoober blop pupperino.","weekend":"Maximum borkdrive super chub you are doing me the shock long bois shoober blop pupperino.","top_skills":"Blogging","gender":"gender neutral","pronouns":"they/them","projects":[p1,p7,p2,p5,p6],"status":true)
User.create!("username":"jsidworth1u","password_digest":"271350aaeb14fdfd4c4699f914b540bc8bb1036511db7a8796cd23f6b56b4def","avatar":"https://randomuser.me/api/portraits/men/39.jpg","first_name":"Junette","last_name":"Sidworth","email":"Junette.Sidworth@datadoghq.com","title":"Project Lead","team":"Engineering","city":"Barcelona","love_datadog":"Maximum borkdrive super chub you are doing me the shock long bois shoober blop pupperino.","weekend":"heckin.","top_skills":"Product magic","gender":"male","pronouns":"he/him","projects":[p5,p6,p3,p1,p7],"status":false)
User.create!("username":"ledlyne1v","password_digest":"3a4deb52798d2059075080693b65d4dde6e184545f7334a0503350f9dddc583a","avatar":"http://www.place-puppy.com/201x201","first_name":"Leupold","last_name":"Edlyne","email":"Leupold.Edlyne@datadoghq.com","title":"HR Director","team":"Human Resources","city":"London","love_datadog":"Waggy wags doing me a frighten woofer very taste wow.","weekend":"Very hand that feed shibe yapper much ruin diet. Yapper noodle horse ruff tungg","top_skills":"Databases","gender":"male","pronouns":"he/him","projects":[p4,p6,p7],"status":false)
User.create!("username":"sverbrugge1w","password_digest":"d7c5668a7fd3443ef2fca234774da19f541a6474b6d6eec61cabe22670438363","avatar":"https://avatars.githubusercontent.com/u/767836?s=200","first_name":"Serge","last_name":"Verbrugge","email":"Serge.Verbrugge@datadoghq.com","title":"UX Manager","team":"Design","city":"New York City","love_datadog":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","weekend":"Maximum borkdrive super chub you are doing me the shock long bois shoober blop pupperino.","top_skills":"Making the client happy","gender":"gender neutral","pronouns":"they/them","projects":[p2,p6,p4,p7],"status":true)
User.create!("username":"espicer1x","password_digest":"003e8b4e37479c2ff2afd4a87ea76f1a6b7f1c30916e882ede46d99c40be19ca","avatar":"https://avatars.githubusercontent.com/u/2860499?s=200","first_name":"Elnar","last_name":"Spicer","email":"Elnar.Spicer@datadoghq.com","title":"Developer","team":"Engineering","city":"Seoul","love_datadog":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","weekend":"heckin.","top_skills":"MVC","gender":"female","pronouns":"she/her","projects":[p6,p4,p7,p5,p2],"status":true)
User.create!("username":"mrenton1y","password_digest":"5d2fb3a9926d4871d30dfd9c798f16959871a4930f2bedefdbd494f263ea8d6d","avatar":"https://randomuser.me/api/portraits/women/2.jpg","first_name":"Martha","last_name":"Renton","email":"Martha.Renton@datadoghq.com","title":"Manager","team":"Finance","city":"","love_datadog":"heckin.","weekend":"Snoot very hand that feed shibe snoot most angery pupper I have ever seen boof pupper very taste wow","top_skills":"MVC","gender":"female","pronouns":"she/her","projects":[p1,p6,p2],"status":false)
User.create!("username":"zkinder1z","password_digest":"6111f84dc9c35226a5b1ec4e3c956551792f56db0bd943aad89b28af0f732f3a","avatar":"http://www.place-puppy.com/201x201","first_name":"Zacherie","last_name":"Kinder","email":"Zacherie.Kinder@datadoghq.com","title":"Project Lead","team":"Engineering","city":"Portland","love_datadog":"Maximum borkdrive super chub you are doing me the shock long bois shoober blop pupperino.","weekend":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","top_skills":"Making Chartz","gender":"female","pronouns":"she/her","projects":[p5,p2,p7,p4,p1],"status":false)
User.create!("username":"owaitland20","password_digest":"51be20f39daf428de3d06c6787953d054456d4f094b308099b003ec2a810581c","avatar":"http://www.place-puppy.com/201x201","first_name":"Osborn","last_name":"Waitland","email":"Osborn.Waitland@datadoghq.com","title":"HR Director","team":"Human Resources","city":"Dublin","love_datadog":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","weekend":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","top_skills":"Financial Planning","gender":"female","pronouns":"she/her","projects":[p4,p5,p6],"status":true)
User.create!("username":"jgerler21","password_digest":"9996223ae143e004432cba931762412ab51320dbb5dcb5d536d7ea067998b366","avatar":"https://avatars.githubusercontent.com/u/2860499?s=200","first_name":"Josefa","last_name":"Gerler","email":"Josefa.Gerler@datadoghq.com","title":"Analyst","team":"Finance","city":"Paris","love_datadog":"heckin.","weekend":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","top_skills":"Databases","gender":"gender neutral","pronouns":"they/them","projects":[p2,p7,p3,p1],"status":false)
User.create!("username":"todowling22","password_digest":"6b809eb1c35230b9961f5028f8c60c58192be4afa8c0d28e86ba2c779c111c18","avatar":"https://avatars.githubusercontent.com/u/577978?s=200","first_name":"Tuck","last_name":"O'Dowling","email":"Tuck.O'Dowling@datadoghq.com","title":"UX Manager","team":"Design","city":"Washington DC","love_datadog":"Very hand that feed shibe yapper much ruin diet. Yapper noodle horse ruff tungg","weekend":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","top_skills":"Blogging","gender":"male","pronouns":"he/him","projects":[p7,p3,p4,p6],"status":false)
User.create!("username":"dbuyers23","password_digest":"56a43680ec6e1384ffa55361f02967cc4eee7ba350e4b23886588a217d010677","avatar":"https://randomuser.me/api/portraits/women/9.jpg","first_name":"Dorian","last_name":"Buyers","email":"Dorian.Buyers@datadoghq.com","title":"Developer","team":"Engineering","city":"Boston","love_datadog":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","weekend":"heckin.","top_skills":"Creating Personas","gender":"gender neutral","pronouns":"they/them","projects":[p2,p4,p7],"status":false)
User.create!("username":"kpountain24","password_digest":"8648172371a105ccc942596cbd2426582f5b16821c7cb48c562a3e42246c5c64","avatar":"https://avatars.githubusercontent.com/u/22248726?s=200","first_name":"Kym","last_name":"Pountain","email":"Kym.Pountain@datadoghq.com","title":"UX Designer","team":"Design","city":"Stockholm","love_datadog":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","weekend":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","top_skills":"Javascript","gender":"female","pronouns":"she/her","projects":[p3,p6,p7,p2],"status":true)
User.create!("username":"eanglin25","password_digest":"36c34bbcd13c3dbf7b22180493ca6fe485035ba09f59a0b874e5209f8f8ab174","avatar":"https://avatars.githubusercontent.com/u/1712393?s=200","first_name":"Eryn","last_name":"Anglin","email":"Eryn.Anglin@datadoghq.com","title":"Developer","team":"Engineering","city":"Denver","love_datadog":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","weekend":"Very hand that feed shibe yapper much ruin diet. Yapper noodle horse ruff tungg","top_skills":"Making Chartz","gender":"gender neutral","pronouns":"they/them","projects":[p3,p7,p4,p6,p1],"status":false)
User.create!("username":"kmacilhargy26","password_digest":"97ce9bf4017ff069103e98918ccf766c8263071b0768a8b7089ccd2e470444f7","avatar":"http://www.place-puppy.com/202x202","first_name":"Kare","last_name":"MacIlhargy","email":"Kare.MacIlhargy@datadoghq.com","title":"Analyst","team":"Finance","city":"Tokyo","love_datadog":"heckin.","weekend":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","top_skills":"Creating Personas","gender":"male","pronouns":"he/him","projects":[p7,p4,p5,p3,p2],"status":true)
User.create!("username":"ccadagan27","password_digest":"b4ebf3e9ce7be27e76601c70e8a875bb23677e6f4817d874d4d1e68d14facd31","avatar":"http://www.place-puppy.com/203x203","first_name":"Cindi","last_name":"Cadagan","email":"Cindi.Cadagan@datadoghq.com","title":"UX Manager","team":"Design","city":"Frankfurt","love_datadog":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","weekend":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","top_skills":"Product magic","gender":"gender neutral","pronouns":"they/them","projects":[p6,p1,p5],"status":true)
User.create!("username":"rmaides28","password_digest":"ad93fa632fc0d0db790b1bec4a7931585653df2691de8dff43ada7a4aa82ecf9","avatar":"https://avatars.githubusercontent.com/u/767836?s=200","first_name":"Rockie","last_name":"Maides","email":"Rockie.Maides@datadoghq.com","title":"Engineer","team":"Engineering","city":"Barcelona","love_datadog":"Very hand that feed shibe yapper much ruin diet. Yapper noodle horse ruff tungg","weekend":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","top_skills":"DevOps","gender":"female","pronouns":"she/her","projects":[p4,p6,p3,p5],"status":true)
User.create!("username":"tmantrup29","password_digest":"7c9ec57b5cef701a6990397ddc90a44ca34987219e062cff41045f6693421f96","avatar":"http://www.place-puppy.com/202x202","first_name":"Thibaut","last_name":"Mantrup","email":"Thibaut.Mantrup@datadoghq.com","title":"Project Lead","team":"Engineering","city":"New York City","love_datadog":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","weekend":"Waggy wags doing me a frighten woofer very taste wow.","top_skills":"Blogging","gender":"gender neutral","pronouns":"they/them","projects":[p2,p3,p1],"status":true)
User.create!("username":"gleftridge2a","password_digest":"80912d5e405300b59d8022d40a4677da8d407e1703a08f4c1c2945a05aa71832","avatar":"https://avatars.githubusercontent.com/u/1510807?s=200","first_name":"Gratia","last_name":"Leftridge","email":"Gratia.Leftridge@datadoghq.com","title":"Engineer","team":"Engineering","city":"Dublin","love_datadog":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","weekend":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","top_skills":"UX Design","gender":"gender neutral","pronouns":"they/them","projects":[p6,p4,p2,p1,p7],"status":true)
User.create!("username":"mcunrado2b","password_digest":"8845e75a76c6e127348d4dca07051dad51b823554265d5ec3e9d05d3dfe1491c","avatar":"https://randomuser.me/api/portraits/women/36.jpg","first_name":"Meridith","last_name":"Cunrado","email":"Meridith.Cunrado@datadoghq.com","title":"Analyst","team":"Finance","city":"São Paulo","love_datadog":"Very hand that feed shibe yapper much ruin diet. Yapper noodle horse ruff tungg","weekend":"Snoot very hand that feed shibe snoot most angery pupper I have ever seen boof pupper very taste wow","top_skills":"Databases","gender":"gender neutral","pronouns":"they/them","projects":[p1,p7,p4,p3],"status":true)
User.create!("username":"atatham2c","password_digest":"ad737d96712197fb496968287c8e3c9d66b6b43e9a9b7ff7d2be778ee7c8932c","avatar":"https://randomuser.me/api/portraits/women/50.jpg","first_name":"Alexine","last_name":"Tatham","email":"Alexine.Tatham@datadoghq.com","title":"UX Designer","team":"Design","city":"Tokyo","love_datadog":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","weekend":"Waggy wags doing me a frighten woofer very taste wow.","top_skills":"Ruby on Rails","gender":"male","pronouns":"he/him","projects":[p6,p4,p1],"status":true)
User.create!("username":"fdoud2d","password_digest":"13f4471607e03412063d8d4b9cff4387faba302c0c7d0a0dbb6434b01d5a07e6","avatar":"http://www.place-puppy.com/200x200","first_name":"Frasier","last_name":"Doud","email":"Frasier.Doud@datadoghq.com","title":"Project Lead","team":"Engineering","city":"Washington DC","love_datadog":"Doggo ipsum such treat big ol doge yapper. Tungg you are doin me a concern.","weekend":"Very hand that feed shibe yapper much ruin diet. Yapper noodle horse ruff tungg","top_skills":"Fly Tweets","gender":"female","pronouns":"she/her","projects":[p5,p2,p6],"status":true)
User.create!("username":"ieloy2e","password_digest":"8a2ad457823617a38a0fc53dcdcc2ea1da3443648181e162aa8f5fd1af004a75","avatar":"https://randomuser.me/api/portraits/women/2.jpg","first_name":"Irma","last_name":"Eloy","email":"Irma.Eloy@datadoghq.com","title":"HR Generalist","team":"Human Resources","city":"Paris","love_datadog":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","weekend":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","top_skills":"Ruby on Rails","gender":"male","pronouns":"he/him","projects":[p3,p4,p6],"status":true)
User.create!("username":"hscalera2f","password_digest":"27154d32b8ae5b19af68b74dee4db7389ceda96c59b05364e398ec0f2b1a563c","avatar":"https://randomuser.me/api/portraits/women/50.jpg","first_name":"Harv","last_name":"Scalera","email":"Harv.Scalera@datadoghq.com","title":"UX Manager","team":"Design","city":"Sydney","love_datadog":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","weekend":"Snoot very hand that feed shibe snoot most angery pupper I have ever seen boof pupper very taste wow","top_skills":"Making the client happy","gender":"gender neutral","pronouns":"they/them","projects":[p4,p6,p7],"status":true)
User.create!("username":"ppusill2g","password_digest":"69f1f24a35612bd897565d61df03630fcb133a1228e6793c930c61706716d6aa","avatar":"https://avatars.githubusercontent.com/u/15220759?s=200","first_name":"Phineas","last_name":"Pusill","email":"Phineas.Pusill@datadoghq.com","title":"HR Generalist","team":"Human Resources","city":"Dublin","love_datadog":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","weekend":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","top_skills":"Ruby on Rails","gender":"gender neutral","pronouns":"they/them","projects":[p6,p3,p2,p7,p1],"status":false)
User.create!("username":"gelnough2h","password_digest":"c9f6b5921988dc9d7ecb9c6f35d6b5434d8f6380c799adb9830f38f35b4f862d","avatar":"https://avatars.githubusercontent.com/u/22248726?s=200","first_name":"Gloria","last_name":"Elnough","email":"Gloria.Elnough@datadoghq.com","title":"Product Manager","team":"Product","city":"Chicago","love_datadog":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","weekend":"Heckin good boys and girls very good spot puggo porgo super chub.  Boof super chub shibe.","top_skills":"UX Design","gender":"female","pronouns":"she/her","projects":[p7,p2,p5,p6,p3],"status":false)
User.create!("username":"hmckinna2i","password_digest":"5c0e9c61a69ce06679ac08ae5930b24b7ff406422689cf9e1bc39d321356557e","avatar":"https://randomuser.me/api/portraits/women/36.jpg","first_name":"Hermione","last_name":"McKinna","email":"Hermione.McKinna@datadoghq.com","title":"Engineer","team":"Engineering","city":"London","love_datadog":"Snoot very hand that feed shibe snoot most angery pupper I have ever seen boof pupper very taste wow","weekend":"Shooberino yapper shibe dat tungg tho long doggo heck very taste wow very hand that feed shibe heckin good boys blop smol borking doggo with a long snoot for pats borking doggo boofers.","top_skills":"Javascript","gender":"gender neutral","pronouns":"they/them","projects":[p4,p7,p2,p5,p6],"status":true)
User.create!("username":"evillage2j","password_digest":"820084cd527bb96790dc1e1b9343344671bf0fb4e2b30adf2eb92252eff74dc2","avatar":"https://avatars.githubusercontent.com/u/1712393?s=200","first_name":"Elita","last_name":"Village","email":"Elita.Village@datadoghq.com","title":"Developer","team":"Engineering","city":"Singapore","love_datadog":"heckin.","weekend":"Waggy wags doing me a frighten woofer very taste wow.","top_skills":"Javascript","gender":"male","pronouns":"he/him","projects":[p6,p3,p5,p1,p7],"status":false)
User.create!("username":"gdullard2k","password_digest":"67f346dbbe7477160ea9d19e203791b99249a7e11af54b4f76f9e4ab4ef64788","avatar":"https://randomuser.me/api/portraits/men/54.jpg","first_name":"Gerti","last_name":"Dullard","email":"Gerti.Dullard@datadoghq.com","title":"UX Manager","team":"Design","city":"San Jose","love_datadog":"Doggo ipsum such treat big ol doge yapper. Tungg you are doin me a concern.","weekend":"Snoot very hand that feed shibe snoot most angery pupper I have ever seen boof pupper very taste wow","top_skills":"Marketing","gender":"female","pronouns":"she/her","projects":[p2,p7,p6],"status":true)
User.create!("username":"rsanderson2l","password_digest":"38730f264cbc99fe88c55e4ec180797026dbf815e9bae886f65fe0a99b0508f6","avatar":"https://randomuser.me/api/portraits/men/54.jpg","first_name":"Regan","last_name":"Sanderson","email":"Regan.Sanderson@datadoghq.com","title":"HR Director","team":"Human Resources","city":"San Francisco","love_datadog":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","weekend":"Snoot very hand that feed shibe snoot most angery pupper I have ever seen boof pupper very taste wow","top_skills":"Project Management","gender":"male","pronouns":"he/him","projects":[p3,p7,p6],"status":true)
User.create!("username":"tkitchingham2m","password_digest":"32bfec08c41113085fdcbf44488a8d5fbc0649688ace236b71d2b91207ce5dc1","avatar":"https://randomuser.me/api/portraits/men/39.jpg","first_name":"Thomasina","last_name":"Kitchingham","email":"Thomasina.Kitchingham@datadoghq.com","title":"Director Product Management","team":"Product","city":"Boston","love_datadog":"Snoot very hand that feed shibe snoot most angery pupper I have ever seen boof pupper very taste wow","weekend":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","top_skills":"Fly Tweets","gender":"female","pronouns":"she/her","projects":[p5,p2,p7,p3,p1],"status":true)
User.create!("username":"acosens2n","password_digest":"89a168026c0eb0c249010e8c1af6d124d427e4300e71174192a90c9c3c815f2c","avatar":"http://www.place-puppy.com/202x202","first_name":"Alyosha","last_name":"Cosens","email":"Alyosha.Cosens@datadoghq.com","title":"Engineer","team":"Engineering","city":"Dublin","love_datadog":"Waggy wags doing me a frighten woofer very taste wow.","weekend":"Snoot very hand that feed shibe snoot most angery pupper I have ever seen boof pupper very taste wow","top_skills":"Ruby on Rails","gender":"male","pronouns":"he/him","projects":[p7,p2,p5,p1,p4],"status":true)
User.create!("username":"rsclanders2o","password_digest":"b925c79962ccbb65b869936e41507d13f5a0b9bb4f0e2517f2e5c41732dd983d","avatar":"https://randomuser.me/api/portraits/women/2.jpg","first_name":"Rollin","last_name":"Sclanders","email":"Rollin.Sclanders@datadoghq.com","title":"HR Generalist","team":"Human Resources","city":"Paris","love_datadog":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","weekend":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","top_skills":"MVC","gender":"gender neutral","pronouns":"they/them","projects":[p3,p4,p6,p5],"status":true)
User.create!("username":"mrisley2p","password_digest":"23412424eca5c8955b6edcdb2ec757299ef28224fe49b15577dd4f3e013783ba","avatar":"https://avatars.githubusercontent.com/u/767836?s=200","first_name":"Maxy","last_name":"Risley","email":"Maxy.Risley@datadoghq.com","title":"Analyst","team":"Finance","city":"Barcelona","love_datadog":"Maximum borkdrive super chub you are doing me the shock long bois shoober blop pupperino.","weekend":"Waggy wags doing me a frighten woofer very taste wow.","top_skills":"Databases","gender":"male","pronouns":"he/him","projects":[p6,p3,p4],"status":false)
User.create!("username":"menstone2q","password_digest":"584661b7d9fcfd033a15b4b61d9d631efeb9af6f591585382423aaa0764490c2","avatar":"http://www.place-puppy.com/201x201","first_name":"Maximilien","last_name":"Enstone","email":"Maximilien.Enstone@datadoghq.com","title":"Director Product Management","team":"Product","city":"New York City","love_datadog":"Ruff tungg heckin I am bekom fat extremely cuuuuuute.  Such treat fluffer.","weekend":"Snoot very hand that feed shibe snoot most angery pupper I have ever seen boof pupper very taste wow","top_skills":"Fly Tweets","gender":"male","pronouns":"he/him","projects":[p3,p7,p5],"status":false)
User.create!("username":"aauchterlony2r","password_digest":"e51f374227b8af7e9932e0771dc0c230ccbb6e16ad26f672516fdc8a48fb11ba","avatar":"http://www.place-puppy.com/200x200","first_name":"Andres","last_name":"Auchterlony","email":"Andres.Auchterlony@datadoghq.com","title":"UX Manager","team":"Design","city":"New York City","love_datadog":"Maximum borkdrive super chub you are doing me the shock long bois shoober blop pupperino.","weekend":"Doggo ipsum such treat big ol doge yapper. Tungg you are doin me a concern.","top_skills":"Databases","gender":"gender neutral","pronouns":"they/them","projects":[p1,p4,p2],"status":false)

p "#{User.count} users with projects were created"

# ----------updates seed: -----------

updates= [{"content":"Just wrapping up the latest round of Usability Testing.","user_id":9},
{"content":"Just had a successful check in meeting with our client. I look forward to updating everyone at our standup tomorrow.","user_id":1},
{"content":"Just wrapping up the latest round of Usability Testing.","user_id":8},
{"content":"I love my teeeeeeam.","user_id":1},
{"content":"Just wrapping up the latest round of Usability Testing.","user_id":4},
{"content":"Just wrapping up the latest round of Usability Testing.","user_id":2},
{"content":"I love my teeeeeeam.","user_id":4},
{"content":"Just wrapping up the latest round of Usability Testing.","user_id":6},
{"content":"Just had a successful check in meeting with our client. I look forward to updating everyone at our standup tomorrow.","user_id":6},
{"content":"Just wrapping up the latest round of Usability Testing.","user_id":7}]

updates.each do |update|
  Update.create! update
end
p "#{Update.count} updates were created"
